task_name: "test_output_names"

# ------------------- 全局配置 -------------------
global:
  max_workers: 1                         # 全局默认并行进程数

# ------------------- 路径管理 -------------------
paths:
  input:
    raw_dialogues_dir: null
    prompt_dir: null
  task_root: "output"

# ------------------- 步骤执行顺序 -------------------
steps_order:
  - "02_split_dialogues"
  - "03_bucket_by_turn"

# ------------------- 各步骤详细配置 -------------------
steps:
  02_split_dialogues:
    enabled: true
    input_json: datas/raw_data/0703/data-simulation-xiaoying-260703.json
    batch_size: 120000
    
    output_names:
      samples: "dialogue_samples"
      turn_distribution: "turn_stats"

  03_bucket_by_turn:
    enabled: true
    manual_buckets:
      - [0, 0]
      - [1, 2]
    
    output_names:
      bucket_prefix: "turn_bucket"
